apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: mlops-a2
type: Opaque
stringData:
  JWT_SECRET: "2d4f0bfed08414a91794b3ee4bfc8ce68c176497983c7bad1298ae0fb8e43541"   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-common
  namespace: mlops-a2
data:
  MONGO_URL: "mongodb://mongo:27017/app"
